;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Cooldownd.Dodge",NewTagName="Cooldown.Dodge")
+GameplayTagRedirects=(OldTagName="Cooldownd",NewTagName="Cooldown")
+GameplayTagList=(Tag="Cooldown.Dodge",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Combo.Close",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Combo.Open",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Input",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Trace",DevComment="")
+GameplayTagList=(Tag="Event.Death",DevComment="")
+GameplayTagList=(Tag="Event.HitReact",DevComment="")
+GameplayTagList=(Tag="Input.Attack",DevComment="")
+GameplayTagList=(Tag="Input.Dodge",DevComment="")
+GameplayTagList=(Tag="Input.Heal",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.HitReact",DevComment="")
+GameplayTagList=(Tag="State.Invincible",DevComment="")

